---
title: "Plotting Results of QED Data Dropout Experiment"
author: "Robert Allaway"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---


```{r}
library(reticulate)
library(tidyverse)

# conda environment:::::

# name: idg-dream
# channels:
#   - defaults
# dependencies:
#   - blas=1.0=mkl
#   - ca-certificates=2019.5.15=1
#   - certifi=2019.6.16=py27_1
#   - intel-openmp=2019.4=233
#   - libcxx=4.0.1=hcfea43d_1
#   - libcxxabi=4.0.1=hcfea43d_1
#   - libedit=3.1.20181209=hb402a30_0
#   - libffi=3.2.1=h475c297_4
#   - libgfortran=3.0.1=h93005f0_2
#   - mkl=2019.4=233
#   - mkl-service=2.3.0=py27hfbe908c_0
#   - mkl_fft=1.0.14=py27h5e564d8_0
#   - mkl_random=1.0.2=py27h27c97d8_0
#   - ncurses=6.1=h0a44026_1
#   - numpy=1.16.5=py27hacdab7b_0
#   - numpy-base=1.16.5=py27h6575580_0
#   - pip=19.2.2=py27_0
#   - python=2.7.16=h97142e2_5
#   - readline=7.0=h1de35cc_5
#   - scikit-learn=0.20.3=py27h27c97d8_0
#   - scipy=1.2.1=py27h1410ff5_0
#   - setuptools=41.0.1=py27_0
#   - sqlite=3.29.0=ha441bb4_0
#   - tk=8.6.8=ha441bb4_0
#   - wheel=0.33.4=py27_0
#   - zlib=1.2.11=h1de35cc_3
#   - pip:
#     - backports-csv==1.0.7
#     - chardet==3.0.4
#     - configparser==4.0.2
#     - deprecated==1.2.4
#     - entrypoints==0.3
#     - enum==0.4.7
#     - future==0.17.1
#     - idna==2.8
#     - keyring==12.0.2
#     - requests==2.22.0
#     - six==1.12.0
#     - synapseclient==1.9.3
#     - urllib3==1.25.4
#     - wrapt==1.11.2
# prefix: //anaconda3/envs/idg-dream

use_condaenv('idg-dream', required = T)
synapse <- import("synapseclient")
syn <- synapse$Synapse()
synutils <- synapse$utils
syn$login()
source_python('https://raw.githubusercontent.com/Sage-Bionetworks/IDG-DREAM-Drug-Kinase-Challenge/master/round1b/score/bin/evaluation_metrics_python2.py')

gold <- syn$get("syn18421225")$path %>% read_csv %>%
  mutate(comp = paste0(Compound_InchiKeys,"_",UniProt_Id,"_",DiscoveRx_Gene_Symbol)) 

spearman_py <- function(gold, pred){
  gold_py <- gold %>% np_array()
  pred_py <- pred %>% np_array()
  spearman(gold_py, pred_py)
}

rmse_py <- function(gold, pred){
  gold_py <- gold %>% np_array()
  pred_py <- pred %>% np_array()
  rmse(gold_py, pred_py)
}

theme_set(theme_bw() +
  theme(text = element_text(size = 15)))

```

```{r}
ids <- tibble::tribble(
  ~id, ~threshold, ~random_iteration, ~is_random, ~exp_label, ~no_of_removed,
  "syn20543796", 0.5, 1, "Random Control", "0.5", 1530,
  "syn20543798", 0.5, 2, "Random Control", "0.5", 1530,
  "syn20543799", 0.5, 3, "Random Control", "0.5", 1530,
  "syn20543800", 0.5, 4, "Random Control", "0.5", 1530,
  "syn20543801", 0.5, 5, "Random Control", "0.5", 1530,
  "syn20543788", 0.5, NA, "Dropout Test", "0.5", 1530,
  "syn20543828", 0.7, 1, "Random Control", "0.7", 330,
  "syn20543829", 0.7, 2, "Random Control", "0.7", 330,
  "syn20543830", 0.7, 3, "Random Control","0.7", 330,
  "syn20543831", 0.7, 4, "Random Control","0.7", 330,
  "syn20543832", 0.7, 5, "Random Control","0.7", 330,
  "syn20543794", 0.7, NA, "Dropout Test","0.7", 330,
  "syn20543834", 0.9, 1, "Random Control","0.9", 56,
  "syn20543835", 0.9, 2, "Random Control","0.9", 56,
  "syn20543837", 0.9, 3, "Random Control","0.9", 56,
  "syn20543838", 0.9, 4, "Random Control","0.9", 56,
  "syn20543839", 0.9, 5, "Random Control","0.9", 56,
  "syn20543795", 0.9, NA, "Dropout Test","0.9", 56,
  "syn18513191", 1, NA, "All Training Data", "AD", 0, 
  "syn20546407", 0.4, NA, "Dropout Test","0.4", 3156,
  "syn20564864", 0.4, 1, "Random Control","0.4", 3156,
  "syn20564865", 0.4, 2, "Random Control","0.4", 3156, 
  "syn20564866", 0.4, 3, "Random Control","0.4", 3156,
  "syn20564867", 0.4, 4, "Random Control","0.4", 3156,
  "syn20564868", 0.4, 5, "Random Control","0.4", 3156,
  "syn20546408", 0.6, NA, "Dropout Test","0.6", 642,
  "syn20564870", 0.6, 1, "Random Control","0.6", 642,
  "syn20564871", 0.6, 2, "Random Control","0.6", 642,
  "syn20564872", 0.6, 3, "Random Control","0.6", 642,
  "syn20564873", 0.6, 4, "Random Control","0.6", 642,
  "syn20564874", 0.6, 5, "Random Control","0.6", 642,
  "syn20546409", 0.8, NA, "Dropout Test","0.8", 136,
  "syn20564875", 0.8, 1, "Random Control","0.8", 136,
  "syn20564876", 0.8, 2, "Random Control","0.8", 136,
  "syn20564877", 0.8, 3, "Random Control","0.8", 136,
  "syn20564878", 0.8, 4, "Random Control","0.8", 136,
  "syn20564879", 0.8, 5, "Random Control","0.8", 136,
  # "syn20546410", 1.0, NA, "Dropout Test", "1.0", "?",
  "syn20564862", 0.2, NA, "Dropout Test","0.2", 37097,
  "syn20574488", 0.2, 1, "Random Control","0.2", 37097,
  "syn20574490", 0.2, 2, "Random Control","0.2", 37097,
  "syn20574491", 0.2, 3, "Random Control","0.2", 37097,
  "syn20574493", 0.2, 4, "Random Control","0.2", 37097,
  "syn20574495", 0.2, 5, "Random Control","0.2", 37097,
  "syn20564863", 0.3, NA, "Dropout Test","0.3", 9186,
  "syn20574503", 0.3, 1, "Random Control","0.3", 9186,
  "syn20574504", 0.3, 2, "Random Control","0.3", 9186,
  "syn20574506", 0.3, 3, "Random Control","0.3", 9186,
  "syn20574508", 0.3, 4, "Random Control","0.3", 9186,
  "syn20574510", 0.3, 5, "Random Control","0.3", 9186,
    "syn20683837", 0.15, 1, "Random Control","0.15", 57633,
    "syn20683838", 0.15, 2, "Random Control","0.15", 57633,
    "syn20683853", 0.15, 3, "Random Control","0.15", 57633,
    "syn20689098", 0.15, 4, "Random Control","0.15", 57633,
    "syn20683839", 0.15, 5, "Random Control","0.15", 57633,
    "syn20683897", 0.15, NA, "Dropout Test","0.15", 57633)

data <- lapply(ids$id, function(x){
  syn$get(x)$path %>% read_csv()
})


names(data) <- ids$id

data_df <- bind_rows(data, .id = "id") %>%
  mutate(comp = paste0(Compound_InchiKeys,"_",UniProt_Id,"_",DiscoveRx_Gene_Symbol)) %>% 
  filter(comp %in% gold$comp)

data_df <- data_df %>% 
  left_join(ids)

data_df_summary <- data_df %>% 
  # group_by(threshold, random_iteration, is_random, Compound_InchiKeys, UniProt_Id, DiscoveRx_Gene_Symbol) %>% 
  # ungroup() %>% 
  left_join(gold %>% select(Compound_InchiKeys, UniProt_Id, DiscoveRx_Gene_Symbol, `pKd_[M]`)) %>% 
  group_by(exp_label, threshold, is_random, random_iteration, no_of_removed) %>% 
  summarize(spearman = spearman_py(`pKd_[M]`,`pKd_[M]_pred`),rmse = rmse_py(`pKd_[M]`,`pKd_[M]_pred`)) %>% 
  arrange(threshold)

ggplot(data_df_summary)+
  geom_point(aes(x =  spearman, y =  rmse, color = as.character(threshold), shape = is_random)) +
  labs(x = "Spearman Correlation", y = "RMSE") +
  scale_color_manual(name="Tanimoto Threshold", values =c("0.1" = "#A80000",
                                                          "0.2" = "#C60968",
                                                          "0.3" = "#C60968",
                                                          "0.4" = "#C61D72",
                                                          "0.5" ="#C64787", 
                                                          "0.6" = "#C884A6",
                                                          "0.7" = "#E8CEE5", 
                                                          "0.8" = "#CCD5FF",
                                                          "0.9" = "#8EA3FF", 
                                                          "1" = "#637FFF",
                                                          "R2" = "#00BFFF")) +
  scale_shape_manual(name = "Random Control", values= c("Random Control"= 1,"Dropout Test"= 19,"All Training Data"=20))

ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_rmse = mean(rmse), sd_rmse = sd(rmse)))+
  geom_col(aes(x = exp_label, y = mean_rmse), fill = "#75B3CE", stat = 'identity') +
  labs(y= "RMSE", x = "Tanimoto Threshold") +
  theme(axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1)) +
  facet_grid(cols = vars(is_random), space = "free", scales = "free") +
  geom_text(aes(x = exp_label, y = mean_rmse, label = signif(no_of_removed/60462,2)), position = position_stack(vjust = 0.5), angle = 90, color = 'white') +
  geom_errorbar(aes(x = exp_label, y = mean_rmse, ymax = mean_rmse+sd_rmse, ymin = mean_rmse-sd_rmse))

ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_spearman = mean(spearman), sd_spearman = sd(spearman)))+
  geom_col(aes(x = exp_label, y = mean_spearman), fill = "#E5A467", stat = 'identity') +
  labs(y= "Spearman Correlation", x = "Tanimoto Threshold") +
  theme(axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1)) +
  facet_grid(cols = vars(is_random), space = "free", scales = "free") +
  geom_text(aes(x = exp_label, y = mean_spearman, label = signif(no_of_removed/60462,3)), position = position_stack(vjust = 0.5), angle = 90, color = 'white') +
    geom_errorbar(aes(x = exp_label, y = mean_spearman, ymax = mean_spearman+sd_spearman, ymin = mean_spearman-sd_spearman))



```

```{r}
ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_rmse = mean(rmse), sd_rmse = sd(rmse)) %>% filter(threshold > 0.1))+
  geom_col(aes(x = exp_label, y = mean_rmse), fill = "#75B3CE", stat = 'identity') +
  labs(y= "RMSE", x = "Tanimoto Threshold") +
  theme(axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1)) +
  facet_grid(cols = vars(is_random), space = "free", scales = "free") +
  geom_text(aes(x = exp_label, y = mean_rmse, label = no_of_removed), position = position_stack(vjust = 0.5), angle = 90, color = 'white') +
  geom_errorbar(aes(x = exp_label, y = mean_rmse, ymax = mean_rmse+sd_rmse, ymin = mean_rmse-sd_rmse))

ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_spearman = mean(spearman), sd_spearman = sd(spearman))  %>% filter(threshold > 0.1))+
  geom_col(aes(x = exp_label, y = mean_spearman), fill = "#E5A467", stat = 'identity') +
  labs(y= "Spearman Correlation", x = "Tanimoto Threshold") +
  theme(axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1)) +
  facet_grid(cols = vars(is_random), space = "free", scales = "free") +
  geom_text(aes(x = exp_label, y = mean_spearman, label = no_of_removed), position = position_stack(vjust = 0.5), angle = 90, color = 'white') +
    geom_errorbar(aes(x = exp_label, y = mean_spearman, ymax = mean_spearman+sd_spearman, ymin = mean_spearman-sd_spearman))

spearman_scal_fact <- 60462*2
rmse_scal_fact <- 60462
  
ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_rmse = mean(rmse), sd_rmse = sd(rmse)) %>% filter(threshold > 0.1))+
  geom_col(aes(x = exp_label, y = mean_rmse), fill = "#75B3CE", stat = 'identity') +
  labs(y= "RMSE", x = "Tanimoto Threshold") +
  theme(axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1)) +
  facet_grid(cols = vars(is_random), space = "free", scales = "free") +
  geom_line(aes(x = exp_label, y = no_of_removed/rmse_scal_fact, group = 1)) +
  geom_errorbar(aes(x = exp_label, y = mean_rmse, ymax = mean_rmse+sd_rmse, ymin = mean_rmse-sd_rmse)) +
  scale_y_continuous(sec.axis = sec_axis(~., name = "Proportion of removed pairs")) 

ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_spearman = mean(spearman), sd_spearman = sd(spearman))  %>% filter(threshold > 0.1))+
  geom_col(aes(x = exp_label, y = mean_spearman), fill = "#E5A467", stat = 'identity') +
  labs(y= "Spearman Correlation", x = "Tanimoto Threshold") +
  theme(axis.text.x = element_text(size= 15, angle = 45, hjust = 1, vjust = 1)) +
  facet_grid(cols = vars(is_random), space = "free", scales = "free") +
    geom_line(aes(x = exp_label, y = no_of_removed/spearman_scal_fact, group = 1)) +
    geom_errorbar(aes(x = exp_label, y = mean_spearman, ymax = mean_spearman+sd_spearman, ymin = mean_spearman-sd_spearman)) + 
  scale_y_continuous(sec.axis = sec_axis(~.*2, name = "Proportion of removed pairs")) 
  

```

```{r}

library(Cairo)

spearman_scal_fact <- 60462*2 ##total no of pairs to convert to ratio
rmse_scal_fact <- 60462*0.6
  
ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_rmse = mean(rmse), sd_rmse = sd(rmse)) %>% filter(threshold > 0.1))+
  geom_bar(aes(x = exp_label, y = mean_rmse, fill = is_random), stat = 'identity', position = position_dodge(preserve = "single")) +
  labs(y= "RMSE", x = "Tanimoto Threshold") +
  theme(axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1)) +
  geom_line(aes(x = exp_label, y = no_of_removed/rmse_scal_fact, group = 1)) +
  geom_point(aes(x = exp_label, y = no_of_removed/rmse_scal_fact, group = 1)) +
  geom_errorbar(aes(x = exp_label, y = mean_rmse, ymax = mean_rmse+sd_rmse, ymin = mean_rmse-sd_rmse, color = is_random), position = 'dodge') +
  scale_y_continuous(sec.axis = sec_axis(~.*0.6, name = "Proportion of removed pairs")) +
  scale_fill_manual(name = "Condition", values= c("Random Control"= "#BFBFBF","Dropout Test"= "#66666E","All Training Data"="#75B3CE")) +
  scale_color_manual(name = "Condition", values= c("Random Control"= "#BFBFBF","Dropout Test"= "#66666E","All Training Data"="#75B3CE"))


ggsave("figure_3_rmse_r2_qed_sim.pdf",  device = cairo_pdf,
              width = 9, height = 4.135, units = "in")
  
  

p2 <- ggplot(data_df_summary %>% group_by(exp_label, is_random, threshold, no_of_removed) %>% summarize(mean_spearman = mean(spearman), sd_spearman = sd(spearman)) %>% filter(threshold > 0.1))+
  geom_bar(aes(x = exp_label, y = mean_spearman, fill = is_random), stat = 'identity', position = position_dodge(preserve = "single")) +
  labs(y= "Spearman correlation", x = "Tanimoto threshold") +
  geom_line(aes(x = exp_label, y = no_of_removed/spearman_scal_fact, group = 1)) +
  geom_point(aes(x = exp_label, y = no_of_removed/spearman_scal_fact, group = 1)) +
  geom_errorbar(aes(x = exp_label, y = mean_spearman, ymax = mean_spearman+sd_spearman, ymin = mean_spearman-sd_spearman, color = is_random), position = 'dodge') +
  scale_y_continuous(sec.axis = sec_axis(~.*2, name = "Proportion of removed pairs")) +
  scale_fill_manual(name = "Condition", values= c("Random Control"= "#BFBFBF","Dropout Test"= "#66666E","All Training Data"="#E5A467")) +
  scale_color_manual(name = "Condition", values= c("Random Control"= "#BFBFBF","Dropout Test"= "#66666E","All Training Data"="#E5A467")) 



ggsave("figure_3_spearman_r2_qed_sim.pdf",  device = cairo_pdf,
              width = 9, height = 4.135, units = "in")


```

## Make Similarity Histogram
```{r}

qed_pkd <- syn$get("syn20690323")$path %>% 
  read_delim(delim = " ", col_names = F) 
qed_cmpd <- syn$get("syn20690840")$path %>% 
  read_delim(delim = "\t", ,col_names = F)
qed_prot <- syn$get("syn20690841")$path %>% 
  read_delim(delim = "\t", col_names = F)

qed_pkd_tidy <- qed_pkd %>% 
  magrittr::set_colnames(qed_prot$X1) %>% 
  magrittr::set_rownames(qed_cmpd$X1) %>% 
  rownames_to_column("cmpd") %>% 
  gather(key = "prot", value = "pKd", -cmpd) %>% 
  filter(pKd < 100)

sim_matrix_path<-syn$get('syn20975467')$path
np <- import("numpy")

sim_mat <- np$load(sim_matrix_path)

colnames(sim_mat) <- qed_cmpd$X1
rownames(sim_mat) <- qed_cmpd$X1

sim_mat_subset <- sim_mat[rownames(sim_mat) %in% gold$Compound_SMILES,] %>% 
  as_tibble(rownames = NA) %>%
  rownames_to_column("test_compounds") %>% 
  group_by(test_compounds) %>% 
  gather("train_compounds", "sim", -test_compounds) %>% 
  ungroup() %>% 
  group_by(train_compounds) %>% 
  top_n(1, sim) %>%
  sample_n(1) %>%  ##in case there are some with identical similarities to test set. we just need to pick one 
  ungroup() %>% 
  rename(cmpd = train_compounds) %>% 
  inner_join(qed_pkd_tidy) %>% 
  filter(!is.na(pKd))

# bars<- tibble::tribble(
#   ~max, ~cutoff, ~height,
#   0.15, 0, -1000,
#   0.2, 0, -1750,
#   0.3, 0,-2500,
#   0.4, 0,-3250,
#   0.5, 0,-4000,
#   0.6, 0,-4750,
#   0.7, 0,-5500,
#   0.8, 0,-6250,
#   0.9, 0,-7000,
# )

p_2 <- ggplot(sim_mat_subset) + 
  geom_histogram(aes(x=sim), boundary = 1, bins = 30)+
  # geom_segment(data = bars, aes(x = max, y = height, xend = cutoff, yend = height), size = 1) +
  labs(x = "Minimum Tanimoto similarity to test compounds", y = "Number of compound-kinase training pairs")  +
  scale_x_continuous(breaks = seq(0,1, by = 0.2)) +
  scale_y_continuous(breaks = scales::breaks_pretty(7))

cowplot::plot_grid(p2, p_2, ncol = 2, align = 'h', axis = 'rl', rel_widths = c(0.5,0.33))

ggsave("figure_3_sim_hist_qed.pdf",  device = cairo_pdf,
               width = 16, height = 4, units = "in")


```

